plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.sonarqube)
}

sonarqube {
    properties {
        property 'sonar.projectKey', 'org.adaway'
        property 'sonar.organization', 'adaway'
        property 'sonar.projectName', 'AdAway'
        property 'sonar.projectVersion', libs.versions.appName.get()
        property 'sonar.host.url', 'https://sonarcloud.io'
    }
}
