plugins {
    alias(libs.plugins.android.library)
}

android {
    compileSdk 37
    namespace = 'io.sentry'

    defaultConfig {
        minSdk 26
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sonarqube {
        skipProject = true
    }
    lint {
        targetSdk 33
    }
    testOptions {
        targetSdk 33
    }
}
