#!/bin/sh
. /etc/rc.common

StartService() {
  if [ "${DNSMASQ:=-NO-}" = "-YES-" ] ; then
    /usr/local/sbin/dnsmasq -q -n
  fi
}

StopService() {
  pid=`GetPID dnsmasq`
  if [ $? -eq 0 ]; then
    kill $pid
  fi
}

RestartService() {
  StopService "$@"
  StartService "$@"
}

RunService "$1"
