name: Android CI

on: [push, pull_request]

jobs:
  build:
    name: Debug build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    
    - run: $ANDROID_HOME/tools/bin/sdkmanager 'ndk;21.0.6113669'

    - name: Run unit tests
      run: ./gradlew test --stacktrace

    - name: Build with Gradle
#      env:
#        key: value
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: AdAway-dev
        path: app/build/outputs/apk/debug/app-debug.apk
